# Generated by Django 4.2.2 on 2023-10-23 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maid',
            old_name='service',
            new_name='service_name',
        ),
    ]
