# Generated by Django 4.2.2 on 2023-10-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_service_maid_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maid',
            name='service_name',
            field=models.CharField(choices=[('Maid', 'Maid'), ('Cook', 'Cook'), ('Nanny', 'Nanny'), ('Care Taker', 'Care Taker')], max_length=100),
        ),
    ]
